Logging:
  IncludeScopes: false
  Debug:
    LogLevel:
      Default: Information
  Console:
    LogLevel:
      Default: Information
eureka:
  client:
    serviceUrl: myDiscoveryService
    validate_certificates: false
